package ee.schimke.composeai.discovery

import kotlinx.serialization.Serializable

/**
 * A screen a builder composed out of components, in the shape a code generator can consume.
 *
 * This is deliberately **not** the UI builder's own document model. It is the narrow subset
 * `ScreenGenerator` needs — which component, what the user set, what went in each slot — so that
 * the generator can be tested and reasoned about without dragging an editor's undo stack, presence
 * state and collaboration protocol along with it. A builder projects its document onto this; the
 * projection is the builder's job and the interesting decisions are not in it.
 */
@Serializable
public data class ScreenDocument(
  /** The generated composable's name. Must be a valid Kotlin identifier — the generator checks. */
  public val name: String,
  public val root: ScreenNode,
  /**
   * State the screen holds, declared before the tree that reads it.
   *
   * A list rather than a map because declaration order is emitted order, and a generated preamble
   * that reshuffles between runs is a diff nobody can review. Names must be unique and usable
   * Kotlin identifiers; the generator refuses otherwise.
   *
   * Empty for a static screen, which is every screen the generator could express before this.
   */
  public val state: List<ScreenState> = emptyList(),
  /** Reusable composables declared in this file, with explicit value and callback parameters. */
  public val functions: List<ScreenFunction> = emptyList(),
)

/**
 * A reusable composable. Its body cannot implicitly capture the screen's state or a caller's row.
 */
@Serializable
public data class ScreenFunction(
  public val name: String,
  public val parameters: List<ScreenParameter>,
  public val root: ScreenNode,
)

/** Function parameters are either concrete values or ordinary zero-argument Unit callbacks. */
@Serializable
public sealed interface ScreenParameter {
  public val name: String

  @Serializable
  public data class Value(public override val name: String, public val typeFqn: String) :
    ScreenParameter

  @Serializable public data class Callback(public override val name: String) : ScreenParameter
}

/**
 * One `mutableStateOf` the generated screen declares.
 *
 * @property name the Kotlin identifier the preamble binds and [ScreenValue.StateRead] names.
 * @property typeFqn what the state holds, checked against the parameter of every read. Declared
 *   rather than inferred from [initial]: a `String?` initialised to null is indistinguishable from
 *   any other nullable, and inferring `Boolean` from `false` would silently forbid a variable that
 *   is meant to widen later.
 * @property initial the starting value, generated by the same rules as any other argument — so a
 *   colour token or a construct works here exactly as it does on a parameter.
 */
@Serializable
public data class ScreenState(
  public val name: String,
  public val typeFqn: String,
  public val initial: ScreenValue,
)

/**
 * One placed component: which one, the arguments the user set, and what they dropped into its
 * slots.
 *
 * @property componentId a `ComponentRecord.canonicalId`, or one of its
 *   `ComponentRecord.componentIds` catalog aliases. Both are accepted because the two sides name
 *   components differently and neither can be made to give: discovery's key is derived
 *   (`app/androidx.compose.material3.TextKt.Text`) precisely so an ordinary preview that carries no
 *   catalog identity still gets one, while a builder's document holds the authored id its palette
 *   was built from (`m3/text`). The record already carries that mapping, so resolving it here beats
 *   asking every builder to rebuild it. An alias claimed by two records is a refusal rather than a
 *   pick, and an id matching nothing is a refusal too — a builder pinned to a catalog it no longer
 *   has is exactly the case where inventing a call site produces confident nonsense.
 * @property arguments values the user set, by **source parameter name**. A name the component does
 *   not declare is a refusal: silently dropping it would generate a screen that compiles and is not
 *   the one that was designed.
 * @property slots children by slot name. A slot the component does not declare is likewise refused.
 * @property slotItems for a slot whose children are declared through its receiver's DSL rather than
 *   composed directly, the member each child is wrapped in — see [SlotItem]. A slot with no entry
 *   emits its children straight into the lambda, which is what every plain `content` slot wants,
 *   and a `TargetParameter.scopeDslReceiver` slot with no entry stays refused.
 */
@Serializable
public data class ScreenNode(
  public val componentId: String,
  public val arguments: Map<String, ScreenValue> = emptyMap(),
  public val slots: Map<String, List<ScreenNode>> = emptyMap(),
  public val slotItems: Map<String, SlotItem> = emptyMap(),
  /**
   * Handlers, by **source parameter name** — `onClick`, not a wire event name.
   *
   * Keyed the same way [arguments] is, and for the same reason: the generator writes a call site
   * against a recovered signature, so the only name it can bind is the one the function declares.
   * Mapping a catalog's event vocabulary onto parameter names is the projection's job, exactly as
   * it is for a property.
   *
   * A parameter that is not a zero-argument function type is refused rather than guessed at.
   */
  public val handlers: Map<String, List<ScreenAction>> = emptyMap(),
  /**
   * Selects one of [slots] instead of calling a component. Such a node has an empty [componentId]
   * and no arguments, handlers or slot items. Wrap it in an ordinary layout node to apply
   * modifiers. Branch children stay in [slots], so document traversal and editing use the same
   * tree.
   */
  public val selection: ScreenSelection? = null,
  /** Repeats one template slot over typed authored rows; introduces no layout of its own. */
  public val repetition: ScreenRepetition? = null,
  /** Calls one of [ScreenDocument.functions], using [arguments] and/or [handlers]. */
  public val function: String? = null,
)

/**
 * A typed row list and a template which reads its innermost row through [ScreenValue.RowRead].
 *
 * [fields] declares the row's value types even when [rows] is empty. Every row must supply exactly
 * these fields. Row values are evaluated in the enclosing scope; template values see the new row.
 * The generator allocates Kotlin identifiers, so field keys remain document data. Wrap this node in
 * an ordinary Column to apply spacing or modifiers. This is eager composition, not lazy items.
 */
@Serializable
public data class ScreenRepetition(
  public val fields: Map<String, String>,
  public val rows: List<Map<String, ScreenValue>>,
  public val templateSlot: String = "body",
)

/**
 * A Kotlin `when` over a scalar value, usually a [ScreenValue.StateRead].
 *
 * [cases] maps child slot names to matching literal values, in emitted order. [elseSlot] names the
 * fallback slot; when absent, an unmatched value composes nothing. Every slot must be named exactly
 * once. Selection introduces no layout or receiver scope and does not retain inactive branches:
 * composition and remembered state follow ordinary Compose `when` behavior.
 */
@Serializable
public data class ScreenSelection(
  public val subject: ScreenValue,
  public val cases: Map<String, ScreenValue>,
  public val elseSlot: String? = null,
)

/**
 * The member of a slot's receiver that each of that slot's children is wrapped in.
 *
 * ## The shape nothing else could express
 *
 * A slot is emitted as `parameter = { child; child }`, which is what a `@Composable () -> Unit`
 * takes and is wrong for a whole family of containers. `LazyColumn`'s `content` is a
 * `LazyListScope.() -> Unit`, and the children of a lazy list are not composed in it — they are
 * **declared** through members of that receiver:
 * ```kotlin
 * LazyColumn(content = {
 *     item { Text(text = "…") }
 *     item { Text(text = "…") }
 * })
 * ```
 *
 * `item` is a member of `LazyListScope`, not a composable, so no arrangement of [ScreenNode]s emits
 * one. That is why every lazy container, the carousel included, had no component record at all: not
 * a missing table row but a missing shape (compose-preview-server#394). A list is not an exotic
 * screen, and a vocabulary that cannot write one is not finished.
 *
 * ## Why it is a claim the generator checks
 *
 * This is [ChainLink.receiverScopeFqn] one level out, and it earns its keep the same way. `item` is
 * a member supplied by the lambda's receiver, so it is never imported and resolves only where that
 * receiver is actually in scope. The generator therefore compares [receiverScopeFqn] against the
 * slot's own recorded receiver — `TargetParameter.scopeDslReceiver`, or
 * `TargetParameter.composableSlotReceiver` for a slot that is composable after all — and refuses a
 * mismatch by name, rather than trusting a projection that says `item` about a `ColumnScope`.
 *
 * The record had to learn to say that. `LazyColumn`'s `content` is **not** `@Composable`, so
 * `composableSlot` was false and the whole container refused as "a parameter, not a @Composable
 * slot"; `TargetParameter.scopeDslReceiver` is the structural signal that separates a scope DSL
 * from an ordinary callback, and a slot is fillable through a [SlotItem] only when it carries one.
 *
 * ## What it deliberately does not carry
 *
 * The receiver of the wrapper's **own** trailing lambda. `LazyListScope.item` composes its body
 * under a `LazyItemScope`, which is what `Modifier.fillParentMaxWidth` needs, and nothing here
 * names it — so a child inside an item sits under no receiver as far as the generator is concerned,
 * and a scoped link there refuses by name exactly as one at the root does. That is the honest
 * answer while no record attests the wrapper's own scope; a field claiming it would be this
 * projection's word for a second fact, and the point of the check above is to have one fewer.
 *
 * @property callable the **simple** name of the member — `item`. Simple rather than qualified
 *   because it is never imported, which is the same reason a scoped [ChainLink] renders only its
 *   last segment. Checked as a writable Kotlin identifier before it is emitted.
 * @property receiverScopeFqn the fully-qualified scope declaring it —
 *   `androidx.compose.foundation.lazy.LazyListScope`. Required, unlike [ChainLink]'s: a wrapper
 *   with no scope to be a member of is a top-level call around a child, which is a thing the
 *   vocabulary has no reason to grow and every reason not to guess at.
 * @property positional arguments before the trailing lambda, generated by the same rules as any
 *   other nested argument. Empty for `item { … }`; `item(key = …)` is what [named] is for.
 * @property named the same, by parameter name.
 */
@Serializable
public data class SlotItem(
  public val callable: String,
  public val receiverScopeFqn: String,
  public val positional: List<ScreenValue> = emptyList(),
  public val named: Map<String, ScreenValue> = emptyMap(),
)

/**
 * One statement a handler runs.
 *
 * Deliberately a closed set of assignments rather than an expression language: a generated lambda
 * that can compute is a generated lambda nobody can review, and the whole claim of this generator
 * is that its output is the screen somebody designed. Everything here writes one declared variable.
 */
@Serializable
public sealed interface ScreenAction {
  /** The variable this action writes. It must be declared in [ScreenDocument.state]. */
  public val variable: String

  /** `expanded.value = !expanded.value` — only valid on a `kotlin.Boolean`. */
  @Serializable public data class Toggle(public override val variable: String) : ScreenAction

  /**
   * `caption.value = "…"` — the value is generated by the same rules as any argument, and is
   * type-checked against the variable's declaration rather than trusted.
   */
  @Serializable
  public data class Set(public override val variable: String, public val value: ScreenValue) :
    ScreenAction
}

/**
 * A value a builder can set on a parameter.
 *
 * ## Two halves, with different guarantees
 *
 * [Text], [Bool], [Whole] and [Fractional] are **self-evidently typed**: the generator knows what
 * `"hello"` and `false` are without being told, so it can reject `text = true` from the record
 * alone. That is the whole reason the first version of this interface held nothing else.
 *
 * It held nothing else for one release. A real builder document sets colours, dimensions, theme
 * tokens, enum entries, paddings and modifier chains, and measured against one — 19 `m3/text`
 * nodes, 18 colour tokens, 14 typography tokens, 11 paddings, 10 layout modifiers — the four
 * literal kinds covered under a third of the values placed. A generator that refuses two thirds of
 * a screen is not a generator anybody uses, so the vocabulary widened to the three shapes below:
 * [Reference] (`MaterialTheme.colorScheme.primary`), [Construct] (`PaddingValues(16.dp)`) and
 * [Chain] (`Modifier.fillMaxWidth()`).
 *
 * ## What the widening costs, stated plainly
 *
 * Those three carry a **claimed** [ScreenValue.typeFqn] rather than an evident one. The generator
 * still checks it against `TargetParameter.typeFqn` and still refuses a mismatch, so a colour
 * handed to a `String` parameter is caught exactly as `text = true` was — but it cannot check that
 * `MaterialTheme.colorScheme.primary` really *is* a `Color`. It takes the projection's word for
 * that one fact.
 *
 * That trade is deliberate and it is the smaller of two evils. The alternative was a table of
 * Material 3's token names inside a library that knows nothing about Material 3, maintained by
 * hand, wrong the first time a design system renamed a token. Instead the design system's own
 * knowledge stays with whoever has it, and what arrives here is a **restricted expression shape**:
 * a dotted path, a call, a chain of extension links. Not free text — every name is checked as
 * writable Kotlin and every reference is emitted fully qualified, so a projection cannot smuggle in
 * `run { System.exit(0) }` or shadow an import.
 *
 * A projection that gets a claimed type wrong produces source that does not compile. That failure
 * is loud, local and lands on the projection — which is the right place for it, and is why the
 * server-side compile check exists.
 */
@Serializable
public sealed interface ScreenValue {

  /**
   * The fully-qualified classifier this value has, or null when the value is its own evidence.
   *
   * Null for the four literal kinds — nothing sensible could be claimed for `Whole(1)`, which fits
   * `Int` and `Long` alike and is checked against whichever the parameter declares.
   */
  public val typeFqn: String?
    get() = null

  /**
   * `@RequiresOptIn` markers the expression needs, declared with `kotlin.RequiresOptIn`.
   *
   * The generator unions these into the wrapper's `@OptIn` exactly as it does for a component's
   * `ComponentCode.requiredOptIns`. It has to be declared rather than derived: a component's
   * markers come from the record, which discovery read off the class file, but a value names an
   * arbitrary allowed callable and nothing here has that callable's annotations. So a projection
   * reaching for an experimental accessor says so, and one that forgets gets a file the compiler
   * rejects — the same trade as [typeFqn], and the same reason it is written down here.
   */
  public val requiredOptIns: List<String>
    get() = emptyList()

  /**
   * The subset of [requiredOptIns] declared with `androidx.annotation.RequiresOptIn`, which needs
   * `@androidx.annotation.OptIn(markerClass = […])` rather than `@kotlin.OptIn` — see
   * `ComponentCode.androidxOptIns` for why the two are not interchangeable.
   */
  public val androidxOptIns: List<String>
    get() = emptyList()

  @Serializable public data class Text(public val value: String) : ScreenValue

  @Serializable public data class Bool(public val value: Boolean) : ScreenValue

  @Serializable public data class Whole(public val value: Long) : ScreenValue

  @Serializable public data class Fractional(public val value: Double) : ScreenValue

  /**
   * A `Float` literal — `1f`.
   *
   * Distinct from [Fractional] because the two differ only in a **spelling** the generator cannot
   * recover anywhere else. Against a declared parameter it does not need to: `Fractional` renders
   * as `1f` for a `kotlin.Float` and `1.0` for a `kotlin.Double`, because the parameter decides. In
   * a **nested** position — a constructor argument, a chain link's argument — there is no declared
   * type to render against, so the rule there is one fixed spelling per literal kind and a fraction
   * is always a `Double`.
   *
   * That rule left `Modifier.weight(…)` inexpressible. It takes a `Float`, it is an argument to a
   * chain link, and `weight(1.0)` does not compile — so a layout weight, which is one of the first
   * things anybody sets in a design tool, had no expression at all. This is the narrow addition
   * that gives it one, rather than making a nested `Fractional` guess at its own precision.
   */
  @Serializable public data class Fractional32(public val value: Float) : ScreenValue

  /**
   * `{ 0.4f }` — a zero-argument lambda whose whole body is [result].
   *
   * ## Why this is not "a lambda" in the general sense
   *
   * Everything else here refuses one, and the KDoc above says so twice: a determinate
   * `LinearProgressIndicator` takes `progress: () -> Float` and was refused because "no
   * `ScreenValue` is a lambda", and `rememberCarouselState { itemCount }` was refused for the same
   * reason one level out. Both were right about the vocabulary and both were pointing at the same
   * narrow gap — **a lambda that returns a value the document already holds**, which is not an
   * expression language and cannot compute anything.
   *
   * That is the whole of it. There are no parameters to bind and no statements to run; the body is
   * one [ScreenValue] generated by exactly the rules any other nested value gets. A generated
   * lambda that could compute would be a generated lambda nobody can review, which is the argument
   * [ScreenAction] makes for being a closed set of assignments, and it still stands.
   *
   * ## What the generator checks
   *
   * The parameter's `TargetParameter.lambdaReturnTypeFqn`, against [result]. Checking the
   * parameter's own `TargetParameter.typeFqn` would be checking almost nothing — every
   * zero-argument function type in the library is a `kotlin.Function0` — so `progress = { "" }`
   * would type-check and fail to compile. A parameter that takes arguments or has a receiver is
   * refused too: `{ 0.4f }` satisfies `(Int) -> Float` only by ignoring the argument it was handed,
   * which is the accident `ComponentSnippets.acceptsZeroArgLambda` exists to catch for handlers.
   */
  @Serializable public data class Lambda(public val result: ScreenValue) : ScreenValue

  /**
   * A zero-argument event callback with the same checked, ordered writes as [ScreenNode.handlers].
   * This can be nested in a call or modifier chain, such as `Modifier.clickable(onClick = …)`. It
   * carries actions rather than source text; every target and assignment is validated.
   */
  @Serializable public data class ActionLambda(public val actions: List<ScreenAction>) : ScreenValue

  /**
   * A read through a fully-qualified path — `androidx.compose.material3.MaterialTheme.colorScheme
   * .primary`, `androidx.compose.ui.text.style.TextAlign.Center`.
   *
   * The [rootFqn] is **imported** and the path written from its simple name, so this reads
   * `Alignment.Start` and `MaterialTheme.colorScheme.primary` — what a person writes.
   *
   * It was emitted fully qualified for a while, and imported nowhere, on the reasoning that an
   * import can be shadowed by a same-named declaration in the package the caller chose for the
   * generated file while a qualified path cannot. The hazard is real and the trade was wrong: a
   * screen names `Modifier` and `MaterialTheme` on nearly every node, so the whole file paid for it
   * — `modifier = androidx.compose.ui.Modifier.size(24.dp)` is not a line anybody writes, and it is
   * half qualified anyway, since the `size` beside it is a [Chain] link and imports. What survives
   * of the reasoning is the conflict check, which refuses two roots claiming one simple name; the
   * caller's own package remains unknowable here, and a collision with it fails at the import line
   * rather than resolving to something else.
   *
   * Nothing about the type claim changes: there is no receiver to infer and no overload to resolve,
   * so the only thing the generator is trusting is still [typeFqn].
   *
   * @property rootFqn the qualified name the path starts from. A class (`…MaterialTheme`), an
   *   object, or a top-level property.
   * @property members further members read from it, in order. Empty for a bare object read.
   */
  @Serializable
  public data class Reference(
    public val rootFqn: String,
    public val members: List<String> = emptyList(),
    public override val typeFqn: String,
    public override val requiredOptIns: List<String> = emptyList(),
    public override val androidxOptIns: List<String> = emptyList(),
  ) : ScreenValue

  /**
   * A call to a fully-qualified callable — `androidx.compose.ui.graphics.Color(0xFF6750A4)`,
   * `androidx.compose.foundation.layout.PaddingValues(16.dp)`.
   *
   * Imported for the same reason [Reference] is, and by the same rule: a top-level declaration
   * imports itself and is written by simple name, while a member of an object imports the object,
   * so `CardDefaults.cardColors(…)` keeps the qualifier a person would write rather than collapsing
   * to a bare `cardColors(…)`. A constructor and a top-level factory function are the same shape
   * here on purpose: `Color(…)` is a function and `PaddingValues(…)` a constructor, the distinction
   * is invisible at the call site, and a record that made a projection declare which one would only
   * give it a second thing to get wrong.
   *
   * @property positional arguments in declaration order.
   * @property named arguments by parameter name, appended after [positional].
   */
  @Serializable
  public data class Construct(
    public val callableFqn: String,
    public val positional: List<ScreenValue> = emptyList(),
    public val named: Map<String, ScreenValue> = emptyMap(),
    public override val typeFqn: String,
    public override val requiredOptIns: List<String> = emptyList(),
    public override val androidxOptIns: List<String> = emptyList(),
  ) : ScreenValue

  /**
   * A receiver followed by extension links — `Modifier.fillMaxWidth().padding(16.dp)`, `16.dp`.
   *
   * The one case that **must** import, and the reason it is a case of its own rather than a
   * [Reference] with a longer path: an extension is resolved from the importing file's scope, so
   * `Modifier.androidx.compose.foundation.layout.fillMaxWidth()` is not a spelling of anything.
   * Each link's callable is imported and called by its simple name, and two links claiming one
   * simple name from different packages are refused — Kotlin calls that a conflicting import, and
   * picking one would silently generate a chain nobody wrote.
   *
   * @property receiver what the links apply to. `Modifier` as a [Reference], or a literal for the
   *   `16` in `16.dp`.
   */
  /**
   * Reads a state variable the document declares.
   *
   * The variable must be declared in [ScreenDocument.state]; a read naming anything else is refused
   * rather than emitted, because the generated file would not compile and the failure would surface
   * as a Kotlin error about a name the designer never typed.
   *
   * Carries no opt-ins of its own: the declaration's [ScreenState.initial] carries them, and it is
   * the expression that actually names an API.
   */
  @Serializable
  public data class StateRead(public val variable: String, public override val typeFqn: String) :
    ScreenValue

  /** A checked read of a field in the innermost repetition's row. Never a source identifier. */
  @Serializable
  public data class RowRead(public val field: String, public override val typeFqn: String) :
    ScreenValue

  /** A checked read of a parameter of the function currently being generated. */
  @Serializable
  public data class ParameterRead(
    public val parameter: String,
    public override val typeFqn: String,
  ) : ScreenValue

  @Serializable
  public data class Chain(
    public val receiver: ScreenValue,
    public val links: List<ChainLink>,
    public override val typeFqn: String,
    public override val requiredOptIns: List<String> = emptyList(),
    public override val androidxOptIns: List<String> = emptyList(),
  ) : ScreenValue
}

/**
 * One link in a [ScreenValue.Chain].
 *
 * @property callableFqn the extension's fully-qualified name. Imported, then called by simple name.
 * @property property a property read (`.dp`) rather than a call (`.padding(8.dp)`). A link that is
 *   both — a property with arguments — is a refusal, not a call.
 */
@Serializable
public data class ChainLink(
  public val callableFqn: String,
  public val positional: List<ScreenValue> = emptyList(),
  public val named: Map<String, ScreenValue> = emptyMap(),
  public val property: Boolean = false,
  /**
   * The **implicit receiver** this link's extension is declared on, when it is a member extension
   * of a slot's scope rather than a top-level one — `androidx.compose.foundation.layout.RowScope`
   * for `Modifier.weight`, `androidx.compose.foundation.layout.BoxScope` for `matchParentSize`.
   *
   * Such a link is *not* imported. `RowScope.weight` is a member of `RowScope`, supplied by the
   * lambda's receiver, and neither `import …layout.RowScope.weight` nor a package-level
   * `…layout.weight` resolves — which is why a capitalised qualifier is otherwise refused outright.
   * What makes it legal instead is **where the node sits**: inside a slot whose
   * `TargetParameter.composableSlotReceiver` is this type, the receiver is in scope and the simple
   * name resolves.
   *
   * So this is a claim the generator **checks** rather than trusts, and it is the only thing that
   * makes a scoped modifier expressible without guessing. A node in a `Column` claiming `RowScope`
   * is refused by name, as is one claiming any scope at the root, where there is no receiver at
   * all. Null for an ordinary top-level extension, which imports as before.
   */
  public val receiverScopeFqn: String? = null,
)
