package ee.schimke.composeai.uibuilder.protocol

import java.io.File
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The published JSON Schemas are the serializers, written down.
 *
 * `src/jvmMain/resources/schemas/` is generated by [ProtocolJsonSchema] from the same descriptors
 * the wire uses, so a field added to `DesignDocumentV1` or a mutation added to `DesignMutationV1`
 * shows up as a diff here rather than as an editor and a validator quietly disagreeing about a
 * document. Run with `UPDATE_SCHEMAS=1` to rewrite the files deliberately after such a change.
 *
 * The committed fixtures are then validated against those files, so a schema that is accurate about
 * the types but wrong about what real documents look like fails too.
 */
class ProtocolJsonSchemaTest {
  private val schemas: Map<String, Pair<String, KSerializer<*>>> =
    mapOf(
      "production-uid-v1.schema.json" to
        ("Production UID (v1)" to
          ee.schimke.composeai.uibuilder.protocol.production.ProductionUidFileV1.serializer()),
      "design-document-v1.schema.json" to ("Design document (v1)" to DesignDocumentV1.serializer()),
      "design-mutation-v1.schema.json" to ("Design mutation (v1)" to DesignMutationV1.serializer()),
      "design-submission-v1.schema.json" to
        ("Design submission (v1)" to DesignSubmissionV1.serializer()),
    )

  @Test
  fun committedSchemasMatchTheSerializers() {
    val update = System.getenv("UPDATE_SCHEMAS") == "1"
    schemas.forEach { (file, spec) ->
      val generated =
        schemaJson.encodeToString(
          JsonObject.serializer(),
          ProtocolJsonSchema.generate(spec.first, spec.second),
        ) + "\n"
      val target = File(schemaDir(), file)
      if (update) target.writeText(generated)
      assertTrue("missing $file - run with UPDATE_SCHEMAS=1", target.isFile)
      assertEquals(
        "$file is stale; regenerate with UPDATE_SCHEMAS=1 ./gradlew :ui-builder-protocol:jvmTest",
        target.readText(),
        generated,
      )
    }
  }

  @Test
  fun everyDocumentFixtureValidatesAgainstTheDocumentSchema() {
    val validator = validator("design-document-v1.schema.json")
    val documents =
      listOf(
        "materialized-confetti.json",
        "materialized-jetcaster.json",
        "materialized-components.json",
      )
    documents.forEach { name ->
      val violations = validator.validate(Json.parseToJsonElement(fixture(name)))
      assertTrue(
        "$name violates the document schema:\n${violations.joinToString("\n")}",
        violations.isEmpty(),
      )
    }
  }

  @Test
  fun theLosslessFixtureValidatesAgainstTheSubmissionAndMutationSchemas() {
    val fixture = Json.parseToJsonElement(fixture("lossless-document-command.json")).jsonObject
    val submissions = validator("design-submission-v1.schema.json")
    val mutations = validator("design-mutation-v1.schema.json")
    val problems = mutableListOf<String>()
    (fixture["submissions"] as kotlinx.serialization.json.JsonArray).forEachIndexed {
      index,
      submission ->
      problems += submissions.validate(submission).map { "submissions[$index]$it" }
      val operations =
        (submission as JsonObject)["operations"] as? kotlinx.serialization.json.JsonArray
      operations?.forEachIndexed { op, mutation ->
        problems += mutations.validate(mutation).map { "submissions[$index].operations[$op]$it" }
      }
    }
    assertTrue(
      "lossless fixture violates the schemas:\n${problems.joinToString("\n")}",
      problems.isEmpty(),
    )
  }

  @Test
  fun aBrokenDocumentIsRejected() {
    val validator = validator("design-document-v1.schema.json")
    val document = Json.parseToJsonElement(fixture("materialized-confetti.json")).jsonObject
    val withoutRoots = JsonObject(document - "roots")
    val unknownField =
      JsonObject(document + ("futureField" to kotlinx.serialization.json.JsonPrimitive(1)))
    assertTrue(validator.validate(withoutRoots).any { "missing roots" in it })
    assertTrue(validator.validate(unknownField).any { "unexpected property futureField" in it })
  }

  @Test
  fun theMutationSchemaListsTheMutationVocabulary() {
    val schema =
      Json.parseToJsonElement(File(schemaDir(), "design-mutation-v1.schema.json").readText())
        .jsonObject
    val defs = schema["\$defs"] as JsonObject
    assertTrue("insertNode missing", defs.keys.any { it.endsWith("insertNode") })
  }

  private fun validator(file: String) =
    SubsetSchemaValidator(Json.parseToJsonElement(File(schemaDir(), file).readText()).jsonObject)

  private fun schemaDir(): File =
    locate("src/jvmMain/resources/schemas", "api/ui-builder-protocol/src/jvmMain/resources/schemas")

  private fun fixture(name: String): String =
    File(locate("docs/ui-builder/protocol-fixtures/v1"), name).readText()

  private fun locate(vararg candidates: String): File {
    var directory: File? = File(System.getProperty("user.dir") ?: ".").absoluteFile
    while (directory != null) {
      candidates.forEach { candidate ->
        File(directory, candidate)
          .takeIf { it.isDirectory }
          ?.let {
            return it
          }
      }
      directory = directory.parentFile
    }
    error("cannot locate any of ${candidates.toList()}")
  }
}
